### ISSUE TITLE
CAN 

### ISSUE THREAD

**Issue by Shahboz78** [Ruturajn/Communication-Between-STM32F407-Discovery-Kit-and-Arduino-UNO-using-CAN-Protocol#1]

**Comment by Ruturajn** [comment]
Hi,
Please let me know, what issue you are facing. I can try to resolve it, although I don't have my board with me currently, but I can try.

Thank you

**Comment by Ruturajn** [comment]
Hi,

Since this issue isn't active since September, I am closing it. You can raise another issue if you are facing some difficulty, or think
that the code has any problems.

Thank You
